"""toppings column changed again 7

Revision ID: 17344333c237
Revises: f46cd13eb909
Create Date: 2020-05-22 13:10:11.758648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17344333c237'
down_revision = 'f46cd13eb909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'is_topper_in_cart',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'is_topper_in_cart',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
