"""toppings column changed again 3

Revision ID: 18411aad86fb
Revises: db9e46b5802a
Create Date: 2020-05-21 23:49:15.157567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18411aad86fb'
down_revision = 'db9e46b5802a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'toppers_limit')
    op.add_column('menu_items', sa.Column('toppers_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'toppers_limit')
    op.add_column('menu', sa.Column('toppers_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
