"""toppings column changed again

Revision ID: 1d7d5e25b218
Revises: 91869c1fa37f
Create Date: 2020-05-21 23:29:32.237081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7d5e25b218'
down_revision = '91869c1fa37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('large_size_price', sa.Integer(), nullable=False))
    op.add_column('menu_items', sa.Column('small_size_price', sa.Integer(), nullable=False))
    op.add_column('menu_items', sa.Column('toppers_limit', sa.Integer(), nullable=True))
    op.drop_column('menu_items', 'small_size')
    op.drop_column('menu_items', 'price')
    op.drop_column('menu_items', 'large_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('large_size', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('menu_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('menu_items', sa.Column('small_size', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'toppers_limit')
    op.drop_column('menu_items', 'small_size_price')
    op.drop_column('menu_items', 'large_size_price')
    # ### end Alembic commands ###
