"""toppings column changed

Revision ID: 2fd3e14a0fd6
Revises: 327d4b40ef01
Create Date: 2020-05-21 20:01:23.425817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fd3e14a0fd6'
down_revision = '327d4b40ef01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('is_topping', sa.Boolean(), nullable=True))
    op.drop_column('menu', 'has_toppings')
    op.drop_column('menu_items', 'is_topper')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_topper', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('menu', sa.Column('has_toppings', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'is_topping')
    # ### end Alembic commands ###
