"""separatig toppers

Revision ID: 327d4b40ef01
Revises: b8548788e506
Create Date: 2020-05-21 19:54:37.415708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '327d4b40ef01'
down_revision = 'b8548788e506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('is_topper', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'is_topper')
    # ### end Alembic commands ###
