"""menu item column renamed

Revision ID: 71234747846f
Revises: 923d09231c71
Create Date: 2020-05-07 21:46:27.959701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71234747846f'
down_revision = '923d09231c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('item_title', sa.String(length=128), nullable=True))
    op.drop_column('menu_items', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('title', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('menu_items', 'item_title')
    # ### end Alembic commands ###
