"""toppings column changed again 5

Revision ID: 8e8ae5fdda43
Revises: a85793a3f815
Create Date: 2020-05-22 02:07:09.899580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8ae5fdda43'
down_revision = 'a85793a3f815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('ordered_size', sa.String(length=40), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'ordered_size')
    # ### end Alembic commands ###
