"""toppings column changed again

Revision ID: 91869c1fa37f
Revises: 2fd3e14a0fd6
Create Date: 2020-05-21 20:16:12.557705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91869c1fa37f'
down_revision = '2fd3e14a0fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('has_toppings', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'has_toppings')
    # ### end Alembic commands ###
