"""menu and menu items relationship

Revision ID: 923d09231c71
Revises: 70bedca2ebf2
Create Date: 2020-05-07 21:06:28.206020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923d09231c71'
down_revision = '70bedca2ebf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_items_menu_id_fkey', 'menu_items', type_='foreignkey')
    op.create_foreign_key(None, 'menu_items', 'menu', ['menu_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.create_foreign_key('menu_items_menu_id_fkey', 'menu_items', 'menu_items', ['menu_id'], ['id'])
    # ### end Alembic commands ###
