"""toppings column changed again 4

Revision ID: a85793a3f815
Revises: 18411aad86fb
Create Date: 2020-05-22 01:43:50.972358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a85793a3f815'
down_revision = '18411aad86fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'price')
    # ### end Alembic commands ###
