"""toppings column added

Revision ID: b8548788e506
Revises: b31676516789
Create Date: 2020-05-21 19:47:02.966362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8548788e506'
down_revision = 'b31676516789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('has_toppings', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'has_toppings')
    # ### end Alembic commands ###
