"""toppings column changed again 2

Revision ID: db9e46b5802a
Revises: 1d7d5e25b218
Create Date: 2020-05-21 23:46:35.005159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9e46b5802a'
down_revision = '1d7d5e25b218'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('toppers_limit', sa.Integer(), nullable=True))
    op.drop_column('menu_items', 'toppers_limit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('toppers_limit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('menu', 'toppers_limit')
    # ### end Alembic commands ###
